services:
  postgres:
    restart: always
    image: postgres:16.3
    environment:
      POSTGRES_DB: "proxyDB"
      POSTGRES_USER: "aa"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5433:5432"
    networks:
      - proxy-network

  proxy:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: build\proxy.Dockerfile
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "proxyDB"
      DB_USER: "aa"
      DB_PASSWORD: "1"
    ports:
      - "8080:8080"
    networks:
      - proxy-network

  api:
    build:
      context: .
      dockerfile: build\api.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    driver: bridge